"""Compatibility exports for core evaluation and rule models."""

from tax_engine.computation import (
    BaseAdjustment,
    BaseInteractionEffect,
    CalculationOperation,
    CalculationStep,
    CalculationTrace,
    ComputationStatus,
    TaxComputationResult,
    TaxDomain,
    TaxInteractionRule,
    TaxTransitionPeriod,
    unresolved_tax_computation,
)
from tax_engine.evaluation import (
    CandidateSupport,
    ClassificationOutcome,
    ClassificationStatus,
    ConditionResult,
    ConditionStatus,
    DecisionStep,
    Evaluation,
    EvaluationContext,
    FactSet,
    RuleDecision,
    RuleDecisionStatus,
    RuleSetRef,
    TaxClassificationCandidate,
    TracePhase,
)
from tax_engine.rule_models import (
    LegalSource,
    RuleVersionRef,
    TaxRuleIdentity,
    TaxRuleVersion,
)

__all__ = [
    "BaseAdjustment",
    "BaseInteractionEffect",
    "CalculationOperation",
    "CalculationStep",
    "CalculationTrace",
    "CandidateSupport",
    "ClassificationOutcome",
    "ClassificationStatus",
    "ComputationStatus",
    "ConditionResult",
    "ConditionStatus",
    "DecisionStep",
    "Evaluation",
    "EvaluationContext",
    "FactSet",
    "LegalSource",
    "RuleDecision",
    "RuleDecisionStatus",
    "RuleSetRef",
    "RuleVersionRef",
    "TaxClassificationCandidate",
    "TaxComputationResult",
    "TaxDomain",
    "TaxInteractionRule",
    "TaxRuleIdentity",
    "TaxRuleVersion",
    "TaxTransitionPeriod",
    "TracePhase",
    "unresolved_tax_computation",
]
